global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker_nodes'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:2019']